"""adding a few columns to item model and reward

Revision ID: 741019596dc2
Revises: 7b3a68112486
Create Date: 2024-09-18 13:04:59.575844

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


schema = SCHEMA if environment == "production" else None

# revision identifiers, used by Alembic.
revision = '741019596dc2'
down_revision = '7b3a68112486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=schema) as batch_op:
        batch_op.add_column(sa.Column('equiped', sa.Boolean(), nullable=False))

    with op.batch_alter_table('rewards', schema=schema) as batch_op:
        batch_op.add_column(sa.Column('equipment', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=schema) as batch_op:
        batch_op.drop_column('equipment')

    with op.batch_alter_table('inventory', schema=schema) as batch_op:
        batch_op.drop_column('equiped')

    # ### end Alembic commands ###
