"""create dailies

Revision ID: ada6a3ffcb95
Revises: d6a4aa8d207c
Create Date: 2024-09-13 12:37:09.071032

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'ada6a3ffcb95'
down_revision = 'd6a4aa8d207c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('Trivial', 'Easy', 'Medium', 'Hard', name='dificulty_level'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('repeats', sa.Enum('Daily', 'Weekly', 'Monthly', 'Yearly', name='repeat_timeframe'), nullable=False),
    sa.Column('repeats_every', sa.Integer(), nullable=True),
    sa.Column('repeats_on', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), nullable=True),
    sa.Column('is_due', sa.Boolean(),nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE dailies SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailies')
    # ### end Alembic commands ###
